name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Test
      run: go test -v ./...
  check-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install gomock
        run: |
          go install go.uber.org/mock/mockgen@latest

      - name: remove mock directory
        run: rm -rf mock

      - name: Check if go generate needs to be run
        run: |
          go generate ./...
          git diff --exit-code
